name: queueapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  firebase_messaging: ^15.1.5
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.6.2

  # UI & Assets
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  intl: ^0.20.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  cupertino_icons: ^1.0.8

  # Utilities
  uuid: ^4.5.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_local_notifications: ^19.5.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.4
  flutter_native_splash: ^2.4.7
  url_launcher_web: ^2.4.1
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.jpg

  # assets:
  #   - assets/images/
  #   - assets/lottie/
